# Auto-generated by agentic-f3dasm
# Timestamp : 2026-06-14T17:17:20+00:00
# Model     : claude-haiku-4-5-20251001
# Run       : /Users/harrislab/Documents/GitHub/f3dasm/studies/agentic_modular_resonance/runs/20260614T163409
#
#!/usr/bin/env python3
"""
Replicate the best modular resonance result from the experimental ledger.
Loads the canonical ExperimentData, identifies the maximum resonance value
within the problem domain (m <= 100000), and asserts against the reported headline.
"""
from f3dasm import ExperimentData

# Load the canonical evaluation ledger
data = ExperimentData.from_file(
    project_dir=r"/Users/harrislab/Documents/GitHub/f3dasm/studies/agentic_modular_resonance/runs/20260614T163409/experiment_data"
)

# Convert to pandas DataFrames: inputs and outputs
df_in, df_out = data.to_pandas()

# Filter to feasible rows (resonance > -1e8) AND domain bounds (m <= 100000)
feasible = df_out[df_out["resonance"] > -1e8]
feasible_idx = feasible.index
domain_feasible = df_in.loc[feasible_idx]
domain_feasible = domain_feasible[domain_feasible["m"] <= 100000]

# Find the row with maximum resonance within domain
best_idx = df_out.loc[domain_feasible.index, "resonance"].idxmax()
best_row_out = df_out.loc[best_idx]
best_row_in = df_in.loc[best_idx]

# Extract the best values
best_k = int(best_row_in["k"])
best_m = int(best_row_in["m"])
best_resonance = float(best_row_out["resonance"])

# Reported headline: best resonance value and the (k, m) pair that achieves it
# within the problem domain [k in 2-50, m in 1000-100000]
REPORTED_K = 11
REPORTED_M = 99761
REPORTED_RESONANCE = 8666.844830638009
TOLERANCE = 0.01

# Assertion: verify both (k, m) and resonance match
assert best_k == REPORTED_K and best_m == REPORTED_M, \
    f"Ledger best (k,m) = ({best_k},{best_m}) does not match reported ({REPORTED_K},{REPORTED_M})"
assert abs(best_resonance - REPORTED_RESONANCE) < TOLERANCE, \
    f"Ledger resonance {best_resonance} does not match reported {REPORTED_RESONANCE}"

print(f"REPLICATED: k={best_k}, m={best_m}, resonance={best_resonance:.6f}")
print(f"Total evaluations in ledger: {len(df_out)}")
print(f"Domain-feasible evaluations: {len(domain_feasible)}")
print(f"Assessment: WITHIN PROBLEM DOMAIN [k in 2-50, m in 1000-100000]")
