# Auto-generated by agentic-f3dasm
# Timestamp : 2026-06-08T15:13:32+00:00
# Model     : claude-haiku-4-5-20251001
# Run       : /Users/harrislab/Documents/GitHub/f3dasm/studies/agentic_supercompressible_3d/runs/20260608T141148
#
#!/usr/bin/env python3
"""
Replicate script for Supercompressible Metamaterial Design (3D) study.
Loads the canonical experiment ledger and reproduces the headline finding:
the design with the highest sigma_crit among coilable==1 (reversible) designs.

This script is fully portable: it searches for experiment_data in the study directory
and its subdirectories.
"""

from f3dasm import ExperimentData
import numpy as np
from pathlib import Path

def find_experiment_data():
    """
    Locate experiment_data directory starting from this script's location.
    Searches in parent directories and runs/ subdirectories.
    """
    script_dir = Path(__file__).parent.resolve()
    
    # Check if experiment_data is in the same directory (study dir)
    candidate = script_dir / "experiment_data"
    if candidate.exists():
        return candidate
    
    # Check in runs/ subdirectories
    runs_dir = script_dir / "runs"
    if runs_dir.exists():
        for run_subdir in runs_dir.iterdir():
            if run_subdir.is_dir():
                candidate = run_subdir / "experiment_data"
                if candidate.exists():
                    return candidate
    
    raise FileNotFoundError(
        f"Could not find experiment_data directory. Searched:\n"
        f"  - {script_dir / 'experiment_data'}\n"
        f"  - {runs_dir}/<any_run>/experiment_data\n"
        f"Expected structure: study_dir/runs/<timestamp>/experiment_data/"
    )

# Locate and load the experiment_data ledger
experiment_data_dir = find_experiment_data()
data = ExperimentData.from_file(project_dir=str(experiment_data_dir))

# Extract inputs and outputs
X = data.input.values  # 1000 x 3 array: [ratio_d, ratio_pitch, ratio_top_diameter]
Y = data.output.values  # 1000 x 3 array: [coilable, sigma_crit, energy]

# Column indices
coilable_col = 0
sigma_crit_col = 1

# Filter to coilable==1 (reversible) designs
coilable = Y[:, coilable_col]
sigma_crit = Y[:, sigma_crit_col]

# Create mask for coilable==1 and valid sigma_crit (not NaN)
feasible = (coilable == 1.0) & ~np.isnan(sigma_crit)

# Extract feasible designs
X_feasible = X[feasible]
sigma_crit_feasible = sigma_crit[feasible]

# Find best design
best_idx = np.argmax(sigma_crit_feasible)
best_sigma_crit = sigma_crit_feasible[best_idx]
best_design = X_feasible[best_idx]

# Map back to original row index for verification
original_indices = np.where(feasible)[0]
best_row_original = original_indices[best_idx]

print("=" * 70)
print("SUPERCOMPRESSIBLE METAMATERIAL DESIGN — OPTIMAL SOLUTION")
print("=" * 70)
print()
print("Objective: Maximize sigma_crit (critical buckling stress, kPa)")
print("Constraint: coilable == 1 (reversible helical coiling, no yielding)")
print()
print("OPTIMAL DESIGN PARAMETERS:")
print(f"  ratio_d = {best_design[0]}")
print(f"  ratio_pitch = {best_design[1]}")
print(f"  ratio_top_diameter = {best_design[2]}")
print()
print("PREDICTED PERFORMANCE:")
print(f"  sigma_crit = {best_sigma_crit:.2f} kPa")
print(f"  coilable = 1 (reversible)")
print()
print(f"Dataset row index: {best_row_original}")
print(f"Total coilable==1 designs in pool: {np.sum(feasible)}")
print()

# Assertion: verify the headline number
assert abs(best_sigma_crit - 93.40867272040576) < 0.01, \
    f"Best sigma_crit {best_sigma_crit} does not match expected 93.41 kPa"

assert abs(best_design[0] - 0.0719892578125) < 0.0001, \
    f"Best ratio_d {best_design[0]} does not match expected 0.07199"

assert abs(best_design[1] - 0.976318359375) < 0.0001, \
    f"Best ratio_pitch {best_design[1]} does not match expected 0.9763"

assert abs(best_design[2] - 0.47734375) < 0.0001, \
    f"Best ratio_top_diameter {best_design[2]} does not match expected 0.4773"

print("✓ REPLICATION VERIFIED")
print(f"  Best sigma_crit: {best_sigma_crit:.6f} kPa (expected: 93.40867 kPa)")
print(f"  Best ratio_d: {best_design[0]:.10f} (expected: 0.0719892578)")
print(f"  Best ratio_pitch: {best_design[1]:.10f} (expected: 0.9763183594)")
print(f"  Best ratio_top_diameter: {best_design[2]:.10f} (expected: 0.4773437500)")
print()
print("=" * 70)
