# Auto-generated by agentic-f3dasm
# Timestamp : 2026-06-11T15:38:16+00:00
# Model     : claude-haiku-4-5-20251001
# Run       : /Users/harrislab/Documents/GitHub/f3dasm/studies/agentic_black_box_8d/runs/20260611T150905
#
#!/usr/bin/env python
"""
Replicate the global minimum found in the 8D black-box optimization study.

This script loads the canonical evaluation ledger (ExperimentData) containing
all 3756 function evaluations across phases D001–D004, identifies the best
(minimum) point, and verifies it matches the reported headline result.

Reported result: f(x) = -1.8060617826300045 at 
  x = [2.859, 2.198, 3.106, 2.432, 3.206, 0.072, 2.392, -0.503]
"""

from f3dasm import ExperimentData
import numpy as np

# Load the canonical evaluation ledger
# The experiment_data_dir is the directory where ExperimentData was serialized
# by the f3dasm pipeline during all evaluation phases (D001–D004).
data = ExperimentData.from_file(project_dir=r"/Users/harrislab/Documents/GitHub/f3dasm/studies/agentic_black_box_8d/runs/20260611T150905/experiment_data")

# Extract inputs (x1..x8) and outputs (f, _delegation_id, etc.)
df_in, df_out = data.to_pandas()

# The objective column is named 'f' (the function value to minimize)
objective_col = 'f'

# Find the point with minimum f(x) across all evaluations
best_idx = df_out[objective_col].idxmin()
best_value = float(df_out.loc[best_idx, objective_col])
best_input = df_in.loc[best_idx].values  # x1..x8

print("=" * 70)
print("REPLICATION: 8D Black-Box Optimization Global Minimum")
print("=" * 70)
print(f"\nTotal evaluations in ledger: {len(data)}")
print(f"Objective column: '{objective_col}'")
print(f"\nBest (minimum) point found:")
print(f"  f(x) = {best_value:.16f}")
print(f"  x    = {best_input}")
print(f"\nExpected headline value: -1.8060617826300045")
print(f"Achieved value:         {best_value:.16f}")

# Verify the result with a tolerance
REPORTED = -1.8060617826300045
TOL = 1e-10
assert abs(best_value - REPORTED) < TOL, (
    f"REPLICATION FAILED: |{best_value} - {REPORTED}| = "
    f"{abs(best_value - REPORTED)} >= tolerance {TOL}"
)

print(f"\n✓ REPLICATED SUCCESSFULLY within tolerance {TOL}")
print("=" * 70)
